/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as ProspectsRouteImport } from './routes/prospects'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWebhooksUnipileRouteImport } from './routes/api/webhooks/unipile'
import { Route as ApiPublicLinkSessionRouteImport } from './routes/api/public/link-session'

const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsRoute = ProspectsRouteImport.update({
  id: '/prospects',
  path: '/prospects',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksUnipileRoute = ApiWebhooksUnipileRouteImport.update({
  id: '/api/webhooks/unipile',
  path: '/api/webhooks/unipile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLinkSessionRoute = ApiPublicLinkSessionRouteImport.update({
  id: '/api/public/link-session',
  path: '/api/public/link-session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/inbox': typeof InboxRoute
  '/onboarding': typeof OnboardingRoute
  '/overview': typeof OverviewRoute
  '/prospects': typeof ProspectsRoute
  '/requests': typeof RequestsRoute
  '/api/public/link-session': typeof ApiPublicLinkSessionRoute
  '/api/webhooks/unipile': typeof ApiWebhooksUnipileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/inbox': typeof InboxRoute
  '/onboarding': typeof OnboardingRoute
  '/overview': typeof OverviewRoute
  '/prospects': typeof ProspectsRoute
  '/requests': typeof RequestsRoute
  '/api/public/link-session': typeof ApiPublicLinkSessionRoute
  '/api/webhooks/unipile': typeof ApiWebhooksUnipileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/inbox': typeof InboxRoute
  '/onboarding': typeof OnboardingRoute
  '/overview': typeof OverviewRoute
  '/prospects': typeof ProspectsRoute
  '/requests': typeof RequestsRoute
  '/api/public/link-session': typeof ApiPublicLinkSessionRoute
  '/api/webhooks/unipile': typeof ApiWebhooksUnipileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connections'
    | '/inbox'
    | '/onboarding'
    | '/overview'
    | '/prospects'
    | '/requests'
    | '/api/public/link-session'
    | '/api/webhooks/unipile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connections'
    | '/inbox'
    | '/onboarding'
    | '/overview'
    | '/prospects'
    | '/requests'
    | '/api/public/link-session'
    | '/api/webhooks/unipile'
  id:
    | '__root__'
    | '/'
    | '/connections'
    | '/inbox'
    | '/onboarding'
    | '/overview'
    | '/prospects'
    | '/requests'
    | '/api/public/link-session'
    | '/api/webhooks/unipile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectionsRoute: typeof ConnectionsRoute
  InboxRoute: typeof InboxRoute
  OnboardingRoute: typeof OnboardingRoute
  OverviewRoute: typeof OverviewRoute
  ProspectsRoute: typeof ProspectsRoute
  RequestsRoute: typeof RequestsRoute
  ApiPublicLinkSessionRoute: typeof ApiPublicLinkSessionRoute
  ApiWebhooksUnipileRoute: typeof ApiWebhooksUnipileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects': {
      id: '/prospects'
      path: '/prospects'
      fullPath: '/prospects'
      preLoaderRoute: typeof ProspectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/unipile': {
      id: '/api/webhooks/unipile'
      path: '/api/webhooks/unipile'
      fullPath: '/api/webhooks/unipile'
      preLoaderRoute: typeof ApiWebhooksUnipileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/link-session': {
      id: '/api/public/link-session'
      path: '/api/public/link-session'
      fullPath: '/api/public/link-session'
      preLoaderRoute: typeof ApiPublicLinkSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectionsRoute: ConnectionsRoute,
  InboxRoute: InboxRoute,
  OnboardingRoute: OnboardingRoute,
  OverviewRoute: OverviewRoute,
  ProspectsRoute: ProspectsRoute,
  RequestsRoute: RequestsRoute,
  ApiPublicLinkSessionRoute: ApiPublicLinkSessionRoute,
  ApiWebhooksUnipileRoute: ApiWebhooksUnipileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
